### ISSUE TITLE
`checkIfNameIsAvailable` does the opposite of what the name and readme suggests

### ISSUE THREAD

**Issue by oplik0** [denorg/x-name#1]
It returns `true` if the name is taken, not if the name is available, and false if the name is available, not if it's taken.
README indicates that `await checkIfNameIsAvailable("abc");` should return `false`, but it returns `true` and `mod_test.ts` check if `await checkIfNameIsAvailable("abc");`  returns `true` - so either the README is wrong and `checkIfNameIsAvailable` is *supposed* to check if the name is taken, or both the code and tests are just wrong.

Only noticed it because I wanted to make it usable from cli, so you don't have to create a new script to check if name is taken, and the output didn't seem to make sense.

**Comment by AnandChowdhary** [comment]
Fixed! I refactored the code earlier today and mistakenly flipped the result.

**Comment by oplik0** [comment]
Ah, you were faster :D

**Comment by AnandChowdhary** [comment]
Haha, thanks for the effort! :)

**Comment by AnandChowdhary** [comment]
Hey, if you want to add a CLI feature (which is super useful!), maybe you can add it in the starter instead? https://github.com/denorg/starter

That way other projects like `up` and `online`, which have great CLI application, can make use of it too. 😄
