### ISSUE TITLE
CLI invoked immediately

### ISSUE THREAD

**Issue by AnandChowdhary** [denorg/x-name#3]
I think it's still a good idea to have a separate `cli.ts`, because I think if we import `x-name` in a different package that has arguments, it will try and run. What do you think, @oplik0?

**Comment by oplik0** [comment]
After a quick test - yeah, that's the case. If you import **and use** `checkIfNameIsAvailable` with Deno.args it will invoke the cli (if you just add import an never use it it doesn't happen actually)
Didn't expect that to happen and I'm glad that I used `cli.ts` in `starter`

But you fixed this before I responded

**Comment by AnandChowdhary** [comment]
It's really interesting that just importing it doesn't trigger, because that's what Node.js would do (if I'm not mistaken). This suggests that it's actually not imported if it's not used, which is pretty efficient!
